<a href="https://colab.research.google.com/github/SurajPatidar201198/Recommendation-system/blob/master/Movie_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
from google.colab import files
uploaded=files.upload()

Saving IMDB_Top250Engmovies2_OMDB_Detailed.csv to IMDB_Top250Engmovies2_OMDB_Detailed.csv


In [0]:
import io
df=pd.read_csv(io.BytesIO(uploaded["IMDB_Top250Engmovies2_OMDB_Detailed.csv"]))

In [0]:
df=df[['Title', 'Director', 'Actors', 'Plot', 'Genre']]

In [0]:
'''print('Rows x Columns : ', df.shape[0], 'x', df.shape[1])
print('Features: ', df.columns.tolist())
print('\nUnique values:')
print(df.nunique())
for col in df.columns:
    print(col, end=': ')
    print(df[col].unique())'''
output=None

In [0]:
df['Title'].nunique()  # gives count of unique values in a perticular column

250

In [0]:
df.columns

Index(['Title', 'Director', 'Actors', 'Plot', 'Genre'], dtype='object')

In [0]:
#DataFrame.iterrows is a generator which yield both index and row
for index,row in df.iterrows():
  print(row['Title'],"-----",row['Genre'])

The Shawshank Redemption ----- Crime, Drama
The Godfather ----- Crime, Drama
The Godfather: Part II ----- Crime, Drama
The Dark Knight ----- Action, Crime, Drama
12 Angry Men ----- Crime, Drama
Schindler's List ----- Biography, Drama, History
The Lord of the Rings: The Return of the King ----- Adventure, Drama, Fantasy
Pulp Fiction ----- Crime, Drama
Fight Club ----- Drama
The Lord of the Rings: The Fellowship of the Ring ----- Adventure, Drama, Fantasy
Forrest Gump ----- Comedy, Drama, Romance
Star Wars: Episode V - The Empire Strikes Back ----- Action, Adventure, Fantasy
Inception ----- Action, Adventure, Sci-Fi
The Lord of the Rings: The Two Towers ----- Adventure, Drama, Fantasy
One Flew Over the Cuckoo's Nest ----- Drama
Goodfellas ----- Crime, Drama
The Matrix ----- Action, Sci-Fi
Star Wars: Episode IV - A New Hope ----- Action, Adventure, Fantasy
Se7en ----- Crime, Drama, Mystery
It's a Wonderful Life ----- Drama, Family, Fantasy
The Silence of the Lambs ----- Crime, Drama, Thri

In [0]:
df

Title  ...                   Genre
0    The Shawshank Redemption  ...            Crime, Drama
1               The Godfather  ...            Crime, Drama
2      The Godfather: Part II  ...            Crime, Drama
3             The Dark Knight  ...    Action, Crime, Drama
4                12 Angry Men  ...            Crime, Drama
..                        ...  ...                     ...
245          The Lost Weekend  ...        Drama, Film-Noir
246             Short Term 12  ...                   Drama
247           His Girl Friday  ...  Comedy, Drama, Romance
248        The Straight Story  ...        Biography, Drama
249       Slumdog Millionaire  ...                   Drama

[250 rows x 5 columns]

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Title     250 non-null    object
 1   Director  250 non-null    object
 2   Actors    250 non-null    object
 3   Plot      250 non-null    object
 4   Genre     250 non-null    object
dtypes: object(5)
memory usage: 9.9+ KB


In [0]:
df.describe().T

count unique                                                top freq
Title      250    250                                     Twelve Monkeys    1
Director   250    155                                   Alfred Hitchcock    9
Actors     250    248  Chris Pratt, Zoe Saldana, Dave Bautista, Vin D...    2
Plot       250    250  A boy who communicates with spirits that don't...    1
Genre      250    110                                              Drama   19

In [0]:
df.loc[(df.Genre == 'Drama')]

Title  ...  Genre
8                         Fight Club  ...  Drama
14   One Flew Over the Cuckoo's Nest  ...  Drama
63               Requiem for a Dream  ...  Drama
81                     All About Eve  ...  Drama
85                 Good Will Hunting  ...  Drama
105                             Room  ...  Drama
121                    Trainspotting  ...  Drama
124                      Gran Torino  ...  Drama
139                          Network  ...  Drama
170                     Paris, Texas  ...  Drama
171            The Last Picture Show  ...  Drama
189  Who's Afraid of Virginia Woolf?  ...  Drama
192                         The Help  ...  Drama
213         A Streetcar Named Desire  ...  Drama
233                      Sling Blade  ...  Drama
235                         Magnolia  ...  Drama
236                         Rain Man  ...  Drama
246                    Short Term 12  ...  Drama
249              Slumdog Millionaire  ...  Drama

[19 rows x 5 columns]

In [0]:
df.Genre.value_counts()

Drama                           19
Crime, Drama                    14
Drama, War                       9
Crime, Drama, Thriller           8
Animation, Adventure, Comedy     8
                                ..
Action, Biography, Drama         1
Drama, Music                     1
Biography, Drama, Thriller       1
Mystery, Romance, Thriller       1
Action, Adventure, Drama         1
Name: Genre, Length: 110, dtype: int64

In [0]:
df.Director.value_counts()

Alfred Hitchcock             9
Stanley Kubrick              8
Billy Wilder                 7
Martin Scorsese              7
Steven Spielberg             7
                            ..
Jon Watts                    1
Lee Unkrich                  1
Stanley Donen, Gene Kelly    1
Stanley Kramer               1
John McTiernan               1
Name: Director, Length: 155, dtype: int64

In [0]:
df['Plot']=df['Plot'].str.replace('[^\w\s]','')

In [0]:
df['Plot']

0      Two imprisoned men bond over a number of years...
1      The aging patriarch of an organized crime dyna...
2      The early life and career of Vito Corleone in ...
3      When the menace known as the Joker emerges fro...
4      A jury holdout attempts to prevent a miscarria...
                             ...                        
245    The desperate life of a chronic alcoholic is f...
246    A 20something supervising staff member of a re...
247    A newspaper editor uses every trick in the boo...
248    An old man makes a long journey by lawnmover t...
249    A Mumbai teen reflects on his upbringing in th...
Name: Plot, Length: 250, dtype: object

In [0]:
pip install rake_nltk

  Created wheel for rake-nltk: filename=rake_nltk-1.0.4-py2.py3-none-any.whl size=7819 sha256=1b65216b6deafd4bd2ddf693bbba80c02a81624264c21eb5d4d1687a97db5b50
  Stored in directory: /root/.cache/pip/wheels/ef/92/fc/271b3709e71a96ffe934b27818946b795ac6b9b8ff8682483f
Successfully built rake-nltk


In [0]:
from rake_nltk import Rake
df['KeyWords']=''
r=Rake()

In [0]:
import nltk
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import warnings
warnings.filterwarnings("ignore")

In [0]:
for index,row in df.iterrows():
  r.extract_keywords_from_text(row['Plot'])
  key_words_dict_scores=r.get_word_degrees()
  row['KeyWords']=list(key_words_dict_scores.keys())

In [0]:
#df.drop(['Key_Words'], axis=1,inplace=True)

In [0]:
df['Plot'][249]

'A Mumbai teen reflects on his upbringing in the slums when he is accused of cheating on the Indian Version of Who Wants to be a Millionaire'

In [0]:
key_words_dict_scores

defaultdict(<function rake_nltk.rake.Rake._build_word_co_occurance_graph.<locals>.<lambda>>,
            {'accused': 1,
             'cheating': 1,
             'indian': 2,
             'millionaire': 1,
             'mumbai': 3,
             'reflects': 3,
             'slums': 1,
             'teen': 3,
             'upbringing': 1,
             'version': 2,
             'wants': 1})

In [0]:
df

Title  ...                                           KeyWords
0    The Shawshank Redemption  ...  [number, acts, eventual, redemption, years, fi...
1               The Godfather  ...  [organized, crime, dynasty, transfers, control...
2      The Godfather: Part II  ...  [career, portrayed, son, michael, expands, tig...
3             The Dark Knight  ...  [dark, knight, must, accept, one, chaos, myste...
4                12 Angry Men  ...  [evidence, justice, prevent, miscarriage, reco...
..                        ...  ...                                                ...
245          The Lost Weekend  ...  [followed, desperate, life, fourday, drinking,...
246             Short Term 12  ...  [residential, treatment, facility, navigates, ...
247           His Girl Friday  ...  [newspaper, editor, uses, every, trick, keep, ...
248        The Straight Story  ...  [mend, long, journey, relationship, old, man, ...
249       Slumdog Millionaire  ...  [accused, indian, version, upbringing, cheatin...

[250 rows x 6 columns]

In [0]:
df['Genre'] = df['Genre'].map(lambda x: x.split(','))

In [0]:
df['Actors'] = df['Actors'].map(lambda x: x.split(','))
df['Director'] = df['Director'].map(lambda x: x.split(','))

In [0]:
for index,rows in df.iterrows():
  rows['Genre']=[x.lower().replace(' ','') for x in rows['Genre']]
  rows['Actors']=[x.lower().replace(' ','') for x in rows['Actors']]
  rows['Director']=[x.lower().replace(' ','') for x in rows['Director']]

In [0]:
df

Title  ...                                           KeyWords
0    The Shawshank Redemption  ...  [number, acts, eventual, redemption, years, fi...
1               The Godfather  ...  [organized, crime, dynasty, transfers, control...
2      The Godfather: Part II  ...  [career, portrayed, son, michael, expands, tig...
3             The Dark Knight  ...  [dark, knight, must, accept, one, chaos, myste...
4                12 Angry Men  ...  [evidence, justice, prevent, miscarriage, reco...
..                        ...  ...                                                ...
245          The Lost Weekend  ...  [followed, desperate, life, fourday, drinking,...
246             Short Term 12  ...  [residential, treatment, facility, navigates, ...
247           His Girl Friday  ...  [newspaper, editor, uses, every, trick, keep, ...
248        The Straight Story  ...  [mend, long, journey, relationship, old, man, ...
249       Slumdog Millionaire  ...  [accused, indian, version, upbringing, cheatin...

[250 rows x 6 columns]

In [0]:
df['Bag_of_Words']=''
columns=['Genre','Director','Actors','KeyWords']

for index,row in df.iterrows():
  words=''
  for col in columns:
    words+=' '.join(row[col])+' '
  row['Bag_of_Words']=words

df['Bag_of_Words']=df['Bag_of_Words'].str.strip().str.replace('   ',' ').str.replace('  ',' ')
df=df[['Title','Bag_of_Words']]
df

Title                                       Bag_of_Words
0    The Shawshank Redemption  crime drama frankdarabont timrobbins morganfre...
1               The Godfather  crime drama francisfordcoppola marlonbrando al...
2      The Godfather: Part II  crime drama francisfordcoppola alpacino robert...
3             The Dark Knight  action crime drama christophernolan christianb...
4                12 Angry Men  crime drama sidneylumet martinbalsam johnfiedl...
..                        ...                                                ...
245          The Lost Weekend  drama film-noir billywilder raymilland janewym...
246             Short Term 12  drama destindanielcretton brielarson johngalla...
247           His Girl Friday  comedy drama romance howardhawks carygrant ros...
248        The Straight Story  biography drama davidlynch sissyspacek janegal...
249       Slumdog Millionaire  drama dannyboyle loveleentandan devpatel saura...

[250 rows x 2 columns]

In [0]:
df['Bag_of_Words'][0]

'crime drama frankdarabont timrobbins morganfreeman bobgunton williamsadler number acts eventual redemption years finding solace common decency two imprisoned men bond'

In [0]:
count = CountVectorizer()
count_matrix = count.fit_transform(df['Bag_of_Words'])
count_matrix

<250x3218 sparse matrix of type '<class 'numpy.int64'>'
	with 5554 stored elements in Compressed Sparse Row format>

In [0]:
df

Title                                       Bag_of_Words
0    The Shawshank Redemption  crime drama frankdarabont timrobbins morganfre...
1               The Godfather  crime drama francisfordcoppola marlonbrando al...
2      The Godfather: Part II  crime drama francisfordcoppola alpacino robert...
3             The Dark Knight  action crime drama christophernolan christianb...
4                12 Angry Men  crime drama sidneylumet martinbalsam johnfiedl...
..                        ...                                                ...
245          The Lost Weekend  drama film-noir billywilder raymilland janewym...
246             Short Term 12  drama destindanielcretton brielarson johngalla...
247           His Girl Friday  comedy drama romance howardhawks carygrant ros...
248        The Straight Story  biography drama davidlynch sissyspacek janegal...
249       Slumdog Millionaire  drama dannyboyle loveleentandan devpatel saura...

[250 rows x 2 columns]

In [0]:
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

[[1.         0.14638501 0.1315587  ... 0.05129892 0.05129892 0.05270463]
 [0.14638501 1.         0.34236839 ... 0.05006262 0.05006262 0.05143445]
 [0.1315587  0.34236839 1.         ... 0.04499213 0.04499213 0.04622502]
 ...
 [0.05129892 0.05006262 0.04499213 ... 1.         0.05263158 0.05407381]
 [0.05129892 0.05006262 0.04499213 ... 0.05263158 1.         0.05407381]
 [0.05270463 0.05143445 0.04622502 ... 0.05407381 0.05407381 1.        ]]


In [0]:
indices = pd.Series(df['Title'])
tep='The Lost Weekend'
indea=list(indices).index('The Lost Weekend')
print(indea)

245


In [0]:
def recommend(title,cosine_sim=cosine_sim):
  recommended_movies=[]
  idx=list(indices).index(title)
  score_series=pd.Series(cosine_sim[idx]).sort_values(ascending=False)
  top_10_indices=list(score_series.iloc[1:11].index)
  for i in top_10_indices:
    recommended_movies.append(list(df['Title'])[i])
  return recommended_movies

In [0]:
recommend('Fargo')

['No Country for Old Men',
 'The Departed',
 'Rope',
 'Reservoir Dogs',
 'The Godfather',
 'The Big Lebowski',
 'The Godfather: Part II',
 'On the Waterfront',
 'Goodfellas',
 'Touch of Evil']

In [0]:
recommend('The Avengers')

['Guardians of the Galaxy Vol. 2',
 'Guardians of the Galaxy',
 'Aliens',
 'The Martian',
 'Terminator 2: Judgment Day',
 'The Terminator',
 'The Thing',
 'Interstellar',
 'Spider-Man: Homecoming',
 'The Matrix']